const BRakhi = [
    {
      id: 1,
      prodId:"BRK101",
      name: "Shree Rakhi",
      img1 : "./budgetRakhi/1.1.jpg",
      img2 : "./budgetRakhi/1.2.jpg",
      img3 : "./budgetRakhi/1.jpg",
      img4 : "./budgetRakhi/1.1.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      category: "Budget Rakhi",
      oldP : 299,
      currP : 199,
      weight:"NA",
      carouselId:"LR1",
      carousel:"#LR1"
    },
    {
        
      id: 2,
      prodId:"BRK102",
      name: "OM Rakhi",
      img1 : "./budgetRakhi/2.1.jpg",
      img2 : "./budgetRakhi/2.2.jpg",
      img3 : "./budgetRakhi/2.jpg",
      img4 : "./budgetRakhi/2.1.jpg",
      modalBox : "#modal_box2",
      modalId:"modal_box2",
      category: "Budget Rakhi",
      oldP : 299,
      currP : 199,
      weight:"NA",
      carouselId:"LR2",
      carousel:"#LR2"
      },{
        id: 3,
      prodId:"BRK103",
      name: "Swastik Rakhi",
      img1 : "./budgetRakhi/3.1.jpg",
      img2 : "./budgetRakhi/3.2.jpg",
      img3 : "./budgetRakhi/3.jpg",
      img4 : "./budgetRakhi/3.1.jpg",
      modalBox : "#modal_box3",
      modalId:"modal_box3",
      category: "Budget Rakhi",
      oldP : 549,
      currP : 299,
      weight:"NA",
      carouselId:"LR3",
      carousel:"#LR3"
      },
      {
        id: 4,
      prodId:"BRK104",
      name: "Round Swastik",
      img1 : "./budgetRakhi/4.1.jpg",
      img2 : "./budgetRakhi/4.2.jpg",
      img3 : "./budgetRakhi/4.jpg",
      img4 : "./budgetRakhi/4.1.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      category: "Budget Rakhi",
      oldP : 399,
      currP : 299,
      weight:"NA",
      carouselId:"LR4",
      carousel:"#LR4"
      },
      {
        id: 5,
      prodId:"BRK105",
      name: "Round OM",
      img1 : "./budgetRakhi/5.1.jpg",
      img2 : "./budgetRakhi/5.2.jpg",
      img3 : "./budgetRakhi/5.jpg",
      img4 : "./budgetRakhi/5.1.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      category: "Budget Rakhi",
      oldP : 399,
      currP :299,
      weight:"NA",
      carouselId:"LR5",
      carousel:"#LR5"
      },{
        id: 6,
      prodId:"BRK106",
      name: "Designer OM",
      img1 : "./budgetRakhi/6.1.jpg",
      img2 : "./budgetRakhi/6.2.jpg",
      img3 : "./budgetRakhi/6.jpg",
      img4 : "./budgetRakhi/6.1.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      category: "Budget Rakhi",
      oldP : 549,
      currP : 399,
      weight:"NA",
      carouselId:"LR6",
      carousel:"#LR6"
      },{
        id: 7,
      prodId:"BRK107",
      name: "Designer Swastik",
      img1 : "./budgetRakhi/7.1.jpg",
      img2 : "./budgetRakhi/7.jpg",
      img3 : "./budgetRakhi/7.1.jpg",
      img4 : "./budgetRakhi/7.jpg",
      modalBox : "#modal_box7",
      modalId:"modal_box7",
      category: "Budget Rakhi",
      oldP : 399,
      currP : 299,
      weight:"NA",
      carouselId:"LR7",
      carousel:"#LR7"
      },{
        id: 8,
      prodId:"BRK108",
      name: "Trishul Rakhi",
      img1 : "./budgetRakhi/8.1.jpg",
      img2 : "./budgetRakhi/8.2.jpg",
      img3 : "./budgetRakhi/8.jpg",
      img4 : "./budgetRakhi/8.1.jpg",
      modalBox : "#modal_box8",
      modalId:"modal_box8",
      category: "Budget Rakhi",
      oldP : 299,
      currP : 199,
      weight:"NA",
      carouselId:"LR8",
      carousel:"#LR8"
      },
  ];
  
  export default BRakhi;