const FRakhi = [
    {
      id: 1,
      prodId:"FRK101",
      name: "Kalash Rakhi",
      img1 : "./Fancyrakhi/1.jpg",
      img2 : "./Fancyrakhi/2.jpg",
      img3 : "./Fancyrakhi/1.jpg",
      img4 : "./Fancyrakhi/2.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      boxName : "Quick View",
      pageName: "",
      category: "Fancy Rakhi",
      oldP : 1049,
      currP : 849,
      weight:"9.900 grams",
      carouselId:"FRK1",
      carousel:"#FRK1"
    },
    {
      id: 2,
      prodId:"FRK102",
      name: "Krishna Rakhi",
      img1 : "./Fancyrakhi/3.jpg",
      img2 : "./Fancyrakhi/3.jpg",
      img3 : "./Fancyrakhi/3.jpg",
      img4 : "./Fancyrakhi/3.jpg",
      modalBox : "#modal_box2",
      modalId:"modal_box2",
      boxName : "Quick View",
      pageName: "",
      category: "Fancy Rakhi",
      oldP :999 ,
      currP : 799,
      weight:"9.200 grams",
      carouselId:"FRK2",
      carousel:"#FRK2"
  
      },{
        id: 3,
      prodId:"FRK103",
      name: "CZ Flower",
      img1 : "./Fancyrakhi/5.jpg",
      img2 : "./Fancyrakhi/6.jpg",
      img3 : "./Fancyrakhi/5.jpg",
      img4 : "./Fancyrakhi/6.jpg",
      modalBox : "#modal_box3",
      modalId:"modal_box3",
      boxName : "Quick Box",
      pageName: "",
      category: "Fancy Rakhi",
      oldP : 1299,
      currP : 1099,
      weight:"12.8 grams",
      carouselId:"FRK3",
      carousel:"#FRK3"
      },
      {
        id: 4,
      prodId:"FRK104",
      name: "Flower Star",
      img1 : "./Fancyrakhi/11.jpg",
      img2 : "./Fancyrakhi/12.jpg",
      img3 : "./Fancyrakhi/11.jpg",
      img4 : "./Fancyrakhi/12.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick Box",
      pageName: "",
      category: "Fancy Rakhi",
      oldP : 1299,
      currP : 1099,
      weight:"8.800 grams",
      carouselId:"FRK4",
      carousel:"#FRK4"
      },
      {
        id: 5,
      prodId:"FRK105",
      name: "Damru Rakhi",
      img1 : "./Fancyrakhi/7.jpg",
      img2 : "./Fancyrakhi/8.jpg",
      img3 : "./Fancyrakhi/7.jpg",
      img4 : "./Fancyrakhi/8.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick Box",
      pageName: "",
      category: "Fancy Rakhi",
      oldP : 949,
      currP : 749,
      weight:"8.600 grams",
      carouselId:"FRK5",
      carousel:"#FRK5"
      },
      {
        id: 6,
      prodId:"FRK106",
      name: "CZ Stone",
      img1 : "./Fancyrakhi/9.jpg",
      img2 : "./Fancyrakhi/10.jpg",
      img3 : "./Fancyrakhi/9.jpg",
      img4 : "./Fancyrakhi/10.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      boxName : "Quick Box",
      pageName: "",
      category: "Fancy Rakhi",
      oldP : 1049,
      currP : 849,
      weight:"9.900 grams",
      carouselId:"FRK6",
      carousel:"#FRK6"
      },
      {
        id: 7,
      prodId:"FRK107",
      name: "Bhai Rakhi",
      img1 : "./Fancyrakhi/13.jpg",
      img2 : "./Fancyrakhi/14.jpg",
      img3 : "./Fancyrakhi/13.jpg",
      img4 : "./Fancyrakhi/14.jpg",
      modalBox : "#modal_box7",
      modalId:"modal_box7",
      boxName : "Quick Box",
      pageName: "",
      category: "Fancy Rakhi",
      oldP : 899,
      currP : 6999,
      weight:"9.900 grams",
      carouselId:"FRK7",
      carousel:"#FRK7"
      },
  ];
  
  export default FRakhi;