const Gchain = [
  {
    id: 1,
      prodId:"GCH101",
      name: "Hollow Chain",
      img1 : "./chainG/1/1.1.jpg",
      img2 : "./chainG/1/1.2.jpg",
      img3 : "./chainG/1/1.3.jpg",
      img4 : "./chainG/1/1.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Chain",
      oldP : 6999,
      currP : 5999,
      weight:"77.6 grams",
      carouselId:"GCH1",
      carousel:"#GCH1",
      size : "N.A"

  },
  {
    id: 2,
    prodId:"GCH102",
    name: "Fine Curved",
    img1 : "./chainG/2/2.jpg",
    img2 : "./chainG/2/2.2.jpg",
    img3 : "./chainG/2/2.3.jpg",
    img4 : "./chainG/2/2.1.jpg",
    modalBox : "#modal_box2",
    modalId:"modal_box2",
    boxName : "Quick View",
    pageName: "",
    category: "Gents Chain",
    oldP : 1999,
    currP : 1199,
    weight:"13 grams",
    carouselId:"GCH2",
    carousel:"#GCH2",
    size : "N.A"

    },{
      id: 3,
      prodId:"GCH103",
      name: "Curved Chain",
      img1 : "./chainG/3/3.jpg",
      img2 : "./chainG/3/3.2.jpg",
      img3 : "./chainG/3/3.3.jpg",
      img4 : "./chainG/3/3.1.jpg",
      modalBox : "#modal_box3",
      modalId:"modal_box3",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Chain",
      oldP : 3299,
      currP : 2499,
      weight:"33.8 grams",
      carouselId:"GCH3",
      carousel:"#GCH3",
      size : "N.A"
    },
    {
      id: 4,
      prodId:"GCH104",
      name: "Hollow Chain",
      img1 : "./chainG/4/4.jpg",
      img2 : "./chainG/4/4.2.jpg",
      img3 : "./chainG/4/4.3.jpg",
      img4 : "./chainG/4/4.1.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Chain",
      oldP : 5299,
      currP : 4299,
      weight:"54.1 grams",
      carouselId:"GCH4",
      carousel:"#GCH4",
      size : "N.A"
    },
    {
      id: 5,
      prodId:"GCH105",
      name: "Snake Chain",
      img1 : "./chainG/5/5.jpg",
      img2 : "./chainG/5/5.2.jpg",
      img3 : "./chainG/5/5.3.jpg",
      img4 : "./chainG/5/5.1.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Chain",
      oldP : 1749,
      currP : 1349,
      weight:"14.1 grams",
      carouselId:"GCH5",
      carousel:"#GCH5",
      size : "N.A"
    },
    {
      id: 6,
      prodId:"GCH106",
      name: "Textured Chain",
      img1 : "./chainG/6/6.jpg",
      img2 : "./chainG/6/6.2.jpg",
      img3 : "./chainG/6/6.3.jpg",
      img4 : "./chainG/6/6.1.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 2099,
      currP : 1599,
      weight:"16.8 grams",
      carouselId:"GCHH6",
      carousel:"#GCH6",
      size : "N.A"
    },
];

export default Gchain;