const Gring = [
    {
      id: 1,
      prodId:"GR101",
      name: "Turtle-1",
      img1 : "./Gring/1.1.jpg",
      img2 : "./Gring/1.jpg",
      img3 : "./Gring/1.1.jpg",
      img4 : "./Gring/1.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 549,
      currP : 449,
      weight:"4.19 grams",
      carouselId:"GR1",
      carousel:"#GR1",
      size : "18"

    },
    {
      id: 2,
      prodId:"GR102",
      name: "Turtle-2",
      img1 : "./Gring/2.1.jpg",
      img2 : "./Gring/2.jpg",
      img3 : "./Gring/2.1.jpg",
      img4 : "./Gring/2.jpg",
      modalBox : "#modal_box2",
      modalId:"modal_box2",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 499,
      currP : 399,
      weight:"3.73 grams",
      carouselId:"GR2",
      carousel:"#GR2",
      size : "20"
  
      },{
        id: 3,
      prodId:"GR103",
      name: "Turtle-3",
      img1 : "./Gring/3.1.jpg",
      img2 : "./Gring/3.jpg",
      img3 : "./Gring/3.1.jpg",
      img4 : "./Gring/3.jpg",
      modalBox : "#modal_box3",
      modalId:"modal_box3",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 559,
      currP : 499,
      weight:"4.57 grams",
      carouselId:"GR3",
      carousel:"#GR3",
      size : "19"
      },
      {
        id: 4,
      prodId:"GR104",
      name: "Band Ring",
      img1 : "./Gring/4.jpg",
      img2 : "./Gring/4.1.jpg",
      img3 : "./Gring/4.jpg",
      img4 : "./Gring/4.1.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 499,
      currP : 349,
      weight:"3.27 grams",
      carouselId:"GR4",
      carousel:"#GR4",
      size : "21"
      },
      {
        id: 5,
      prodId:"GR105",
      name: "White Pearl",
      img1 : "./Gring/5.jpg",
      img2 : "./Gring/5.jpg",
      img3 : "./Gring/5.jpg",
      img4 : "./Gring/5.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 399,
      currP : 299,
      weight:"2.54 grams",
      carouselId:"GR5",
      carousel:"#GR5",
      size : "19"
      },
      {
        id: 6,
      prodId:"GR106",
      name: "Pearl Ring",
      img1 : "./Gring/6.jpg",
      img2 : "./Gring/6.1.jpg",
      img3 : "./Gring/6.jpg",
      img4 : "./Gring/6.1.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      boxName : "Quick View",
      pageName: "",
      category: "Gents Ring",
      oldP : 459,
      currP : 329,
      weight:"2.80 grams",
      carouselId:"GR6",
      carousel:"#GR6",
      size : "20"
      },
  ];
  
  export default Gring;