const Lbracelet = [
    {
      id: 1,
      prodId:"LBR101",
      name: "Sap Green Flower",
      img1 : "./bracelet/1.jpg",
      img2 : "./bracelet/1.1.jpg",
      img3 : "./bracelet/1.jpg",
      img4 : "./bracelet/1.1.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Bracelet",
      oldP : 1299,
      currP : 899,
      weight:"7.240 grams",
      carouselId:"LBR1",
      carousel:"#LBR1",
      size : "N.A"
    },
    {
      id: 2,
      prodId:"LBR102",
      name: "White Stone Drop",
      img1 : "./bracelet/2.jpg",
      img2 : "./bracelet/2.1.jpg",
      img3 : "./bracelet/2.jpg",
      img4 : "./bracelet/2.1.jpg",
      modalBox : "#modal_box2",
      modalId:"modal_box2",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Bracelet",
      oldP : 1299,
      currP : 899,
      weight:"7.340 grams",
      carouselId:"LBR2",
      carousel:"#LBR2",
      size : "N.A"
  
      },{
        id: 3,
      prodId:"LBR103",
      name: "Green Flower",
      img1 : "./bracelet/3.jpg",
      img2 : "./bracelet/1.1.jpg",
      img3 : "./bracelet/1.jpg",
      img4 : "./bracelet/1.1.jpg",
      modalBox : "",
      modalId:"",
      boxName : "Sold Out",
      pageName: "",
      category: "Ladies Bracelet",
      oldP : 1299,
      currP : 899,
      weight:"7.240 grams",
      carouselId:"LBR1",
      carousel:"#LBR1",
      size : "N.A"
      },
      {
        id: 4,
      prodId:"LBR104",
      name: "Doube D",
      img1 : "./bracelet/4.jpg",
      img2 : "./bracelet/4.1.jpg",
      img3 : "./bracelet/4.jpg",
      img4 : "./bracelet/4.1.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Bracelet",
      oldP : 1249,
      currP : 849,
      weight:"6.760 grams",
      carouselId:"LBR4",
      carousel:"#LBR4",
      size : "N.A"
      },
      {
        id: 5,
      prodId:"LBR105",
      name: "Pink Stone Infinity",
      img1 : "./bracelet/5.jpg",
      img2 : "./bracelet/5.1.jpg",
      img3 : "./bracelet/5.jpg",
      img4 : "./bracelet/5.1.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Bracelet",
      oldP : 1599,
      currP : 1099,
      weight:"9.090 grams",
      carouselId:"LBR5",
      carousel:"#LBR5",
      size : "N.A"
      },
  ];
  
  export default Lbracelet;