const Locket = [
    {
      id: 1,
      prodId:"DLC101",
      name: "OM Locket-1",
      img1 : "./pendant/1.jpg",
      img2 : "./pendant/1.jpg",
      img3 : "./pendant/1.jpg",
      img4 : "./pendant/1.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 399,
      currP : 299,
      weight:"2.350 grams",
      carouselId:"DLC1",
      carousel:"#DLC1",
      size : "N.A"
    },
    {
      id: 2,
      prodId:"DLC102",
      name: "OM Locket-2",
      img1 : "./pendant/2.jpg",
      img2 : "./pendant/2.jpg",
      img3 : "./pendant/2.jpg",
      img4 : "./pendant/2.jpg",
      modalBox : "#modal_box2",
      modalId:"modal_box2",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 379,
      currP : 279,
      weight:"2.000 grams",
      carouselId:"DLC2",
      carousel:"#DLC2",
      size : "N.A"
  
      },{
        id: 3,
      prodId:"DLC103",
      name: "Heart OM",
      img1 : "./pendant/3.jpg",
      img2 : "./pendant/3.jpg",
      img3 : "./pendant/3.jpg",
      img4 : "./pendant/3.jpg",
      modalBox : "#modal_box3",
      modalId:"modal_box3",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 349,
      currP : 249,
      weight:"1.640 grams",
      carouselId:"DLC3",
      carousel:"#DLC3",
      size : "N.A"
      },
      {
        id: 4,
      prodId:"DLC104",
      name: "OM Locket-3",
      img1 : "./pendant/4.jpg",
      img2 : "./pendant/4.jpg",
      img3 : "./pendant/4.jpg",
      img4 : "./pendant/4.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 379,
      currP : 279,
      weight:"2.070 grams",
      carouselId:"DLC4",
      carousel:"#DLC4",
      size : "N.A"
      },
      {
        id: 5,
      prodId:"DLC105",
      name: "Trishul Locket",
      img1 : "./pendant/5.jpg",
      img2 : "./pendant/5.jpg",
      img3 : "./pendant/5.jpg",
      img4 : "./pendant/5.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 399,
      currP : 299,
      weight:"2.420 grams",
      carouselId:"DLC5",
      carousel:"#DLC5",
      size : "N.A"
      },
      {
        id: 6,
      prodId:"DLC106",
      name: "Star OM",
      img1 : "./pendant/6.jpg",
      img2 : "./pendant/6.jpg",
      img3 : "./pendant/6.jpg",
      img4 : "./pendant/6.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 349,
      currP : 249,
      weight:"1.56 grams",
      carouselId:"DLC6",
      carousel:"#DLC6",
      size : "N.A"
      },
      {
        id: 7,
      prodId:"DLC107",
      name: "OM Locket-4",
      img1 : "./pendant/7.jpg",
      img2 : "./pendant/7.jpg",
      img3 : "./pendant/7.jpg",
      img4 : "./pendant/7.jpg",
      modalBox : "#modal_box7",
      modalId:"modal_box7",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 399,
      currP : 279,
      weight:"2.060 grams",
      carouselId:"DLC7",
      carousel:"#DLC7",
      size : "N.A"
      },
      {
        id: 8,
      prodId:"DLC108",
      name: "OM Locket-5",
      img1 : "./pendant/8.jpg",
      img2 : "./pendant/8.jpg",
      img3 : "./pendant/8.jpg",
      img4 : "./pendant/8.jpg",
      modalBox : "#modal_box8",
      modalId:"modal_box8",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 499,
      currP : 349,
      weight:"2.850 grams",
      carouselId:"DLC8",
      carousel:"#DLC8",
      size : "N.A"
      },
      {
        id: 9,
      prodId:"DLC109",
      name: "Circle OM",
      img1 : "./pendant/9.jpg",
      img2 : "./pendant/9.jpg",
      img3 : "./pendant/9.jpg",
      img4 : "./pendant/9.jpg",
      modalBox : "#modal_box9",
      modalId:"modal_box9",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 349,
      currP : 249,
      weight:"1.680 grams",
      carouselId:"DLC9",
      carousel:"#DLC9",
      size : "N.A"
      },
      {
        id: 10,
      prodId:"DLC110",
      name: "Star Locket",
      img1 : "./pendant/10.jpg",
      img2 : "./pendant/10.1.jpg",
      img3 : "./pendant/10.jpg",
      img4 : "./pendant/10.1.jpg",
      modalBox : "#modal_box10",
      modalId:"modal_box10",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 499,
      currP : 349,
      weight:"2.720 grams",
      carouselId:"DLC10",
      carousel:"#DLC10",
      size : "N.A"
      },
      {
        id: 11,
      prodId:"DLC101",
      name: "Shree Ram",
      img1 : "./pendant/11.jpg",
      img2 : "./pendant/11.1.jpg",
      img3 : "./pendant/11.jpg",
      img4 : "./pendant/11.1.jpg",
      modalBox : "#modal_box11",
      modalId:"modal_box11",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 499,
      currP : 599,
      weight:"4.00 grams",
      carouselId:"DLC11",
      carousel:"#DLC11",
      size : "N.A"
      },
      {
        id: 12,
      prodId:"DLC112",
      name: "Shiv Locket",
      img1 : "./pendant/12.jpg",
      img2 : "./pendant/12.1.jpg",
      img3 : "./pendant/12.jpg",
      img4 : "./pendant/12.1.jpg",
      modalBox : "#modal_box12",
      modalId:"modal_box12",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 549,
      currP : 449,
      weight:"3.760 grams",
      carouselId:"DLC12",
      carousel:"#DLC12",
      size : "N.A"
      },
      {
        id: 13,
      prodId:"DLC113",
      name: "Hanuman Gada-1",
      img1 : "./pendant/13.1.jpg",
      img2 : "./pendant/13.jpg",
      img3 : "./pendant/13.2.jpg",
      img4 : "./pendant/13.jpg",
      modalBox : "#modal_box13",
      modalId:"modal_box13",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 349,
      currP : 249,
      weight:"2.000 grams",
      carouselId:"DLC13",
      carousel:"#DLC13",
      size : "N.A"
      },
      {
        id: 14,
      prodId:"DLC114",
      name: "Hanuman Gada-2",
      img1 : "./pendant/14.jpg",
      img2 : "./pendant/14.1.jpg",
      img3 : "./pendant/14.jpg",
      img4 : "./pendant/14.1.jpg",
      modalBox : "#modal_box14",
      modalId:"modal_box14",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 349,
      currP : 249,
      weight:"2.110 grams",
      carouselId:"DLC14",
      carousel:"#DLC14",
      size : "N.A"
      },
      {
        id: 15,
      prodId:"DLC115",
      name: "Hanuman Gada-3",
      img1 : "./pendant/15.1.jpg",
      img2 : "./pendant/15.jpg",
      img3 : "./pendant/15.1.jpg",
      img4 : "./pendant/15.jpg",
      modalBox : "#modal_box15",
      modalId:"modal_box15",
      boxName : "Quick View",
      pageName: "",
      category: "Divine Locket",
      oldP : 399,
      currP : 279,
      weight:"2.220 grams",
      carouselId:"DLC15",
      carousel:"#DLC15",
      size : "N.A"
      },
  ];
  
  export default Locket;