const Lring = [
    {
      id: 1,
      prodId:"LR101",
      name: "Z Ring",
      img1 : "./Lring/1.jpg",
      img2 : "./Lring/1.jpg",
      img3 : "./Lring/1.jpg",
      img4 : "./Lring/1.jpg",
      modalBox : "",
      modalId:"",
      boxName : "Sold Out",
      pageName: "",
      category: "Ladies Ring",
      oldP : 499,
      currP : 349,
      weight:"",
      carouselId:"LR1",
      carousel:"#LR1",
      size : ""
    },
    {
      id: 2,
      prodId:"LR102",
      name: "Flower Ring",
      img1 : "./Lring/2.2.jpg",
      img2 : "./Lring/1.jpg",
      img3 : "./Lring/1.jpg",
      img4 : "./Lring/1.jpg",
      modalBox : "",
      modalId:"",
      boxName : "Sold Out",
      pageName: "",
      category: "Ladies Ring",
      oldP : 329,
      currP : 229,
      weight:"",
      carouselId:"LR2",
      carousel:"#LR2",
      size : ""
  
      },{
        id: 3,
      prodId:"LR103",
      name: "Green Stone",
      img1 : "./Lring/3.1.jpg",
      img2 : "./Lring/1.jpg",
      img3 : "./Lring/1.jpg",
      img4 : "./Lring/1.jpg",
      modalBox : "",
      modalId:"",
      boxName : "Sold Out",
      pageName: "",
      category: "Ladies Ring",
      oldP : 499,
      currP : 349,
      weight:"",
      carouselId:"LR3",
      carousel:"#LR3",
      size : ""
      },
      {
        id: 4,
      prodId:"LR104",
      name: "Modern Ring",
      img1 : "./Lring/4.1.jpg",
      img2 : "./Lring/4.jpg",
      img3 : "./Lring/4.1.jpg",
      img4 : "./Lring/4.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 429,
      currP : 349,
      weight:"",
      carouselId:"LR4",
      carousel:"#LR4",
      size : "13"
      },
      {
        id: 5,
      prodId:"LR105",
      name: "Round Star",
      img1 : "./Lring/5.1.jpg",
      img2 : "./Lring/5.jpg",
      img3 : "./Lring/5.1.jpg",
      img4 : "./Lring/5.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 499,
      currP : 379,
      weight:"2.82 grams",
      carouselId:"LR5",
      carousel:"#LR5",
      size : "11"

      },
      {
        id: 6,
      prodId:"LR106",
      name: "S Ring",
      img1 : "./Lring/6.1.jpg",
      img2 : "./Lring/6.jpg",
      img3 : "./Lring/6.1.jpg",
      img4 : "./Lring/6.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 499,
      currP : 349,
      weight:"2.46 grams",
      carouselId:"LR6",
      carousel:"#LR6",
      size : "11"

      },
      {
        id: 7,
      prodId:"LR107",
      name: "Mini Flower",
      img1 : "./Lring/7.1.jpg",
      img2 : "./Lring/7.jpg",
      img3 : "./Lring/7.1.jpg",
      img4 : "./Lring/7.jpg",
      modalBox : "#modal_box7",
      modalId:"modal_box7",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 399,
      currP : 299,
      weight:"2.19 grams",
      carouselId:"LR7",
      carousel:"#LR7",
      size : "11"

      },
      {
        id: 8,
      prodId:"LR108",
      name: "Leaf Ring",
      img1 : "./Lring/8.1.jpg",
      img2 : "./Lring/8.jpg",
      img3 : "./Lring/8.1.jpg",
      img4 : "./Lring/8.jpg",
      modalBox : "#modal_box8",
      modalId:"modal_box8",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 399,
      currP : 249,
      weight:"1.44 grams",
      carouselId:"LR8",
      carousel:"#LR8",
      size : "11"

      },
      {
      id: 9,
      prodId:"LR109",
      name: "Leaf Flower Ring",
      img1 : "./Lring/9.2.jpg",
      img2 : "./Lring/9.jpg",
      img3 : "./Lring/9.2.jpg",
      img4 : "./Lring/9.1.jpg",
      modalBox : "#modal_box9",
      modalId:"modal_box9",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 329,
      currP : 249,
      weight:"1.68 grams",
      carouselId:"LR9",
      carousel:"#LR9",
      size : "13"

      },
      {
        id: 10,
      prodId:"LR110",
      name: "Flower Ring",
      img1 : "./Lring/10.2.jpg",
      img2 : "./Lring/4.1.jpg",
      img3 : "./Lring/4.jpg",
      img4 : "./Lring/4.1.jpg",
      modalBox : "",
      modalId:"",
      boxName : "Sold Out",
      pageName: "",
      category: "Ladies Ring",
      oldP : 339,
      currP : 249,
      weight:"",
      carouselId:"",
      carousel:"",
      size : "11"

      },
      {
        id: 11,
      prodId:"LR111",
      name: "Channel Flower",
      img1 : "./Lring/11.2.jpg",
      img2 : "./Lring/11.1.jpg",
      img3 : "./Lring/11.2.jpg",
      img4 : "./Lring/11.jpg",
      modalBox : "#modal_box11",
      modalId:"modal_box11",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 359,
      currP : 279,
      weight:"1.84 grams",
      carouselId:"LR11",
      carousel:"#LR11",
      size : "11"

      },
      {
        id: 12,
      prodId:"LR112",
      name: "Long Leaf",
      img1 : "./Lring/12.1.jpg",
      img2 : "./Lring/12.jpg",
      img3 : "./Lring/12.2.jpg",
      img4 : "./Lring/12.jpg",
      modalBox : "#modal_box12",
      modalId:"modal_box12",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 349,
      currP : 249,
      weight:"1.54 grams",
      carouselId:"LR12",
      carousel:"#LR12",
      size : "14"

      },
      {
        id: 13,
      prodId:"LR113",
      name: "White Stone",
      img1 : "./Lring/13.2.jpg",
      img2 : "./Lring/13.1.jpg",
      img3 : "./Lring/13.2.jpg",
      img4 : "./Lring/13.jpg",
      modalBox : "#modal_box13",
      modalId:"modal_box13",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 399,
      currP : 299,
      weight:"2.15 grams",
      carouselId:"LR13",
      carousel:"#LR13",
      size : "11"

      },
      {
        id: 14,
      prodId:"LR114",
      name: "Turtle-1",
      img1 : "./Lring/14.1.jpg",
      img2 : "./Lring/14.jpg",
      img3 : "./Lring/14.jpg",
      img4 : "./Lring/14.1.jpg",
      modalBox : "#modal_box14",
      modalId:"modal_box14",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 339,
      currP : 249,
      weight:"1.67 grams",
      carouselId:"LR14",
      carousel:"#LR14",
      size : "12"

      },
      {
        id: 15,
      prodId:"LR115",
      name: "Red Turtle",
      img1 : "./Lring/15.1.jpg",
      img2 : "./Lring/15.jpg",
      img3 : "./Lring/15.jpg",
      img4 : "./Lring/15.1.jpg",
      modalBox : "#modal_box15",
      modalId:"modal_box15",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 359,
      currP : 299,
      weight:"2.24 grams",
      carouselId:"LR15",
      carousel:"#LR15",
      size : "11"

      },
      {
        id: 16,
      prodId:"LR116",
      name: "Turtle-2",
      img1 : "./Lring/16.1.jpg",
      img2 : "./Lring/16.jpg",
      img3 : "./Lring/16.jpg",
      img4 : "./Lring/16.1.jpg",
      modalBox : "#modal_box16",
      modalId:"modal_box16",
      boxName : "Quick View",
      pageName: "",
      category: "Ladies Ring",
      oldP : 359,
      currP : 299,
      weight:"2.17 grams",
      carouselId:"LR16",
      carousel:"#LR16",
      size : "14"

      },
  ];
  
  export default Lring;