const Sawan = [
  {
    id: 1,
      prodId:"SAC101",
      name: "Shivling",
      img1 : "./sawan/1.1.jpg",
      img2 : "./sawan/1.2.jpg",
      img3 : "./sawan/1.jpg",
      img4 : "./sawan/1.1.jpg",
      modalBox : "#modal_box1",
      modalId:"modal_box1",
      boxName : "Quick View",
      pageName: "",
      category: "Sawan Collection",
      oldP : 1299,
      currP : 1199,
      weight:"11.26 grams",
      carouselId:"SAC1",
      carousel:"#SAC1",
      size : "N.A"

  },
  {
    id: 2,
    prodId:"SAC102",
    name: "Nandi",
    img1 : "./sawan/2.jpg",
    img2 : "./sawan/2.2.jpg",
    img3 : "./sawan/2.1.jpg",
    img4 : "./sawan/2.jpg",
    modalBox : "#modal_box2",
    modalId:"modal_box2",
    boxName : "Quick View",
    pageName: "",
    category: "Sawan Collection",
    oldP : 699,
    currP : 599,
    weight:"5.79 grams",
    carouselId:"SAC2",
    carousel:"#SAC2",
    size : "N.A"


    },{
      id: 3,
      prodId:"SAC103",
      name: "Long Trishul",
      img1 : "./sawan/3.jpg",
      img2 : "./sawan/3.1.jpg",
      img3 : "./sawan/3.jpg",
      img4 : "./sawan/3.1.jpg",
      modalBox : "#modal_box3",
      modalId:"modal_box3",
      boxName : "Quick View",
      pageName: "",
      category: "Sawan Collection",
      oldP : 799,
      currP : 649,
      weight:"6.00 grams",
      carouselId:"SAC3",
      carousel:"#SAC3",
      size : "N.A"

    },
    {
      id: 4,
      prodId:"SAC104",
      name: "Trishul",
      img1 : "./sawan/4.jpg",
      img2 : "./sawan/4.1.jpg",
      img3 : "./sawan/4.jpg",
      img4 : "./sawan/4.1.jpg",
      modalBox : "#modal_box4",
      modalId:"modal_box4",
      boxName : "Quick View",
      pageName: "",
      category: "Sawan Collection",
      oldP : 699,
      currP : 549,
      weight:"5.48 grams",
      carouselId:"SAC4",
      carousel:"#SAC4",
      size : "N.A"

    },
    {
      id: 5,
      prodId:"SAC105",
      name: "Bell Patra",
      img1 : "./sawan/5.jpg",
      img2 : "./sawan/5.1.jpg",
      img3 : "./sawan/5.2.jpg",
      img4 : "./sawan/5.jpg",
      modalBox : "#modal_box5",
      modalId:"modal_box5",
      boxName : "Quick View",
      pageName: "",
      category: "Sawan Collection",
      oldP : 249,
      currP : 199,
      weight:"1.63 grams",
      carouselId:"SAC5",
      carousel:"#SAC5",
      size : "N.A"

    },
    {
      id: 6,
      prodId:"SAC106",
      name: "Combine",
      img1 : "./sawan/6.jpg",
      img2 : "./sawan/6.1.jpg",
      img3 : "./sawan/6.2.jpg",
      img4 : "./sawan/6.jpg",
      modalBox : "#modal_box6",
      modalId:"modal_box6",
      boxName : "Quick View",
      pageName: "",
      category: "Sawan Collection",
      oldP : 2699,
      currP : 2499,
      weight:"24.16 grams",
      carouselId:"SAC6",
      carousel:"#SAC6",
      size : "N.A"

    },
];

export default Sawan;